services:
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.116.1
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/services/identity/Identity.Api/Dockerfile
    depends_on:
      - otel-collector

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    depends_on:
      - otel-collector

