services:

  # Contenedores de Infrastructura [Observabilidad]
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.116.1
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:latest

  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus/prometheus.yml" ]
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - zipkin

  # Contenedores de Aplicación
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/services/identity/Identity.Api/Dockerfile
    depends_on:
      - otel-collector

  address.api:
    image: ${DOCKER_REGISTRY-}addressapi
    build:
      context: .
      dockerfile: src/services/address/Address.Api/Dockerfile

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    depends_on:
      - otel-collector
